// v1.2.0: ascension is always available; only newly reached floors settle rewards.
const ASCENSION_V120=Object.freeze({schema:2,milestones:[2000,3000,5000,8000],base:{attack:.10,hp:.10,defense:.095,resource:.15,fate:.11},anchors:[[0,0,0,0,0,0],[1250,.08,.08,.08,.12,.08],[2000,.108,.108,.099,.168,.128],[2035,.11,.11,.10,.17,.13],[2450,.122,.122,.116,.184,.136],[3000,.15,.15,.1425,.25,.17],[5000,.25,.25,.2375,.40,.26],[8000,.34,.34,.323,.55,.36]],decayPerAscension:.25});
function emptyAscension(){return {schema:2,bonuses:{attack:0,hp:0,defense:0,resource:0,fate:0},lastFloor:0,legacyCount:0,legacyFateTotal:0,history:[]}}
function nonnegativeFinite(value,fallback=0){let n=Number(value);return Number.isFinite(n)&&n>=0?n:fallback}
function migrateAscension(state,source){state.floor=Math.max(1,Math.floor(nonnegativeFinite(source.floor,1)));state.bestFloor=Math.max(state.floor,Math.floor(nonnegativeFinite(source.bestFloor,1)));state.ascensions=Math.floor(nonnegativeFinite(source.ascensions));let old=source.ascension,a=emptyAscension();if(old&&[1,2].includes(old.schema)){for(let key of Object.keys(a.bonuses))a.bonuses[key]=nonnegativeFinite(old.bonuses?.[key]);a.lastFloor=Math.floor(nonnegativeFinite(old.lastFloor));a.legacyCount=Math.min(state.ascensions,Math.floor(nonnegativeFinite(old.legacyCount)));a.legacyFateTotal=nonnegativeFinite(old.legacyFateTotal);a.history=Array.isArray(old.history)?old.history.slice(-50):[]}else{a.legacyCount=state.ascensions;a.legacyFateTotal=nonnegativeFinite(state.fateTotal);a.lastFloor=state.ascensions?state.bestFloor:0}if(state.ascensions&&!a.lastFloor)a.lastFloor=state.bestFloor;state.ascension=a;return state}
function ascensionCurve(highest=S.bestFloor,count=S.ascensions){let floor=Math.min(8000,nonnegativeFinite(highest)),anchors=ASCENSION_V120.anchors;if(floor<=0)return {attack:0,hp:0,defense:0,resource:0,fate:0};let right=anchors.findIndex(a=>a[0]>=floor);if(right<1)right=anchors.length-1;let lo=anchors[right-1],hi=anchors[right],t=Math.max(0,Math.min(1,(floor-lo[0])/(hi[0]-lo[0]))),decay=1/(1+nonnegativeFinite(count)*ASCENSION_V120.decayPerAscension),reward={};Object.keys(ASCENSION_V120.base).forEach((key,i)=>reward[key]=Math.round((lo[i+1]+(hi[i+1]-lo[i+1])*t)*decay*1e9)/1e9);return reward}
function ascensionReward(highest=S.bestFloor,count=S.ascensions,claimedFloor=0){let current=ascensionCurve(highest,count),claimed=ascensionCurve(Math.min(nonnegativeFinite(highest),nonnegativeFinite(claimedFloor)),count),out={};for(let key of Object.keys(current))out[key]=Math.max(0,Math.round((current[key]-claimed[key])*1e9)/1e9);return out}
function currentAscensionReward(state=S){return ascensionReward(state.bestFloor,state.ascensions,state.ascension?.lastFloor||0)}
function nextAscensionFloor(state=S){let last=Math.max(state.bestFloor,state.ascension?.lastFloor||0);return ASCENSION_V120.milestones.find(f=>f>last)||Math.ceil(Math.max(1,last)*1.5/100)*100}
function ascensionEligibility(state=S){let claimed=state.ascension?.lastFloor||0,repeat=state.bestFloor<=claimed;return {ready:true,repeat,required:0,remaining:0,reason:repeat?'当前没有新增最高层，本次收益为 0；仍可飞升，但次数会增加并降低后续收益':'随时可以飞升；只结算上次飞升后新增最高层的收益'}}
function ascensionBonus(key){return nonnegativeFinite(S.ascension?.bonuses?.[key])}function ascensionResourceMult(){return 1+ascensionBonus('resource')}function ascensionPercent(n){return '+'+(n*100).toFixed(1).replace(/\.0$/,'')+'%'}
function ascensionEffectRows(b){return [['attack','攻击'],['hp','生命'],['defense','防御'],['resource','资源获取'],['fate','仙缘获取']].map(([key,name])=>`<div class="asc-effect"><span class="has-tip" tabindex="0" data-tip="${name}是飞升后永久叠加的倍率。">${name}</span><b data-asc-effect="${key}">${ascensionPercent(b[key]||0)}</b></div>`).join('')}
let ascensionViewSignature='',ascensionReturnFocus=null;
function ascensionPreviewHtml(){let c=ascensionEligibility(),gain=currentAscensionReward(),a=S.ascension,decay=1/(1+S.ascensions*.25),next=nextAscensionFloor(),future=ascensionReward(next,S.ascensions,a.lastFloor||0);return `<div class="asc-progress"><b>当前最高层：<span data-asc-floor>${S.bestFloor}</span></b><span>飞升次数：${S.ascensions}</span></div><p class="asc-condition ${c.repeat?'warn':''}" role="status">${c.repeat?'!':'✓'} ${c.reason}</p>${S.ascensions?`<h3>当前累计效果</h3><div class="asc-effects">${ascensionEffectRows(a.bonuses)}</div>`:''}<h3>本次实时收益</h3><div class="asc-effects">${ascensionEffectRows(gain)}</div><p class="small muted">第 ${S.ascensions+1} 次收益系数：${decay.toFixed(3)}。最高层变化时自动刷新。</p><p>${next}层累计可结算预览：攻击 ${ascensionPercent(future.attack)} · 资源 ${ascensionPercent(future.resource)}</p><span class="help-dot has-tip" tabindex="0" data-tip="飞升保留武将、装备、灵宠、功法、神兵、塔层、境界和修为，只增加永久属性、资源速度与仙缘效率。">?</span>${a.legacyCount||a.legacyFateTotal?`<p class="small muted">旧存档永久倍率 ×${ascMult().toFixed(2)} 已保留。</p>`:''}`}
function renderAscensionPreview(force=false){if(!S?.ascension)return;let signature=JSON.stringify([S.bestFloor,S.ascensions,S.ascension]);if(!force&&signature===ascensionViewSignature)return;ascensionViewSignature=signature;let html=ascensionPreviewHtml(),c=ascensionEligibility();for(let id of ['ascDetail','ascModalBody']){let el=document.getElementById(id);if(el)el.innerHTML=html}for(let id of ['ascBtn','ascHeaderBtn']){let el=document.getElementById(id);if(el){el.disabled=false;el.textContent='飞升 · 可确认';el.setAttribute('aria-haspopup','dialog')}}let confirm=document.getElementById('ascConfirmBtn');if(confirm){confirm.dataset.unavailable='false';confirm.dataset.reason='';confirm.textContent=c.repeat?'仍要飞升（收益 0）':'确认飞升'}let count=document.getElementById('ascCount');if(count)count.textContent=S.ascensions;decorateTerms?.()}
function openAscension(){renderAscensionPreview(true);let dialog=document.getElementById('ascensionDialog');ascensionReturnFocus=document.activeElement;if(!dialog.open){if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','')}document.getElementById('ascCloseBtn').focus()}function closeAscension(){let d=document.getElementById('ascensionDialog');if(typeof d.close==='function')d.close();else d.removeAttribute('open');ascensionReturnFocus?.focus?.()}
function ascend(){let reward=currentAscensionReward(),old=S.ascension,oldCount=S.ascensions,hpRatio=playerHP/Math.max(1,totalStats().hp),bonuses={};for(let key of Object.keys(reward))bonuses[key]=Math.round((old.bonuses[key]+reward[key])*1e9)/1e9;S.ascension={...old,schema:2,bonuses,lastFloor:Math.max(old.lastFloor||0,S.bestFloor),history:[...old.history,{floor:S.bestFloor,count:oldCount+1,reward,at:Date.now()}].slice(-50)};S.ascensions=oldCount+1;if(!save(false)){S.ascension=old;S.ascensions=oldCount;toast('飞升未完成：保存失败，请导出存档后重试');return false}playerHP=Math.max(0,hpRatio*totalStats().hp);render();renderAscensionPreview(true);toast(`飞升成功 · 攻击 ${ascensionPercent(reward.attack)} · 资源 ${ascensionPercent(reward.resource)} · 成长进度已保留`);return true}
